Jenkinsfile (Declarative Pipeline)

pipeline {
    agent { docker { image 'maven:3.3.3' } }
    stages {
        stage('build') {
            steps {
                sh 'echo "Hello world"'
                sh '''
                                    echo "Multiline shell steps works too"
                                    ls -lah
                                '''
            }
        }
    }
}

